export const AIRBUS320Seats: any = {
  A: [{number: 1, isVip: false, slot: true},
{number: 2, isVip: false, slot: true},
{number: 3, isVip: false, slot: true},
{number: 4, isVip: false, slot: true},
{number: 5, isVip: false, slot: true},
{number: 6, isVip: false, slot: true},
{number: 7, isVip: false, slot: true},
{number: 8, isVip: false, slot: true},
{number: 9, isVip: false, slot: true},
{number: 10, isVip: false, slot: true},
{number: 11, isVip: false, slot: true},
{number: 12, isVip: false, slot: true},
{number: 13, isVip: false, slot: true},
{number: 14, isVip: false, slot: true},
{number: 15, isVip: false, slot: true},
{number: 16, isVip: false, slot: true},
{number: 17, isVip: false, slot: true},
{number: 18, isVip: false, slot: true},
{number: 19, isVip: false, slot: true},
{number: 20, isVip: false, slot: true},
{number: 21, isVip: false, slot: true},
{number: 22, isVip: false, slot: true},
{number: 23, isVip: false, slot: true},
{number: 24, isVip: false, slot: true},
{number: 25, isVip: false, slot: true}],
  B: [{number: 1, isVip: false, slot: true},
    {number: 2, isVip: false, slot: true},
    {number: 3, isVip: false, slot: true},
    {number: 4, isVip: false, slot: true},
    {number: 5, isVip: false, slot: true},
    {number: 6, isVip: false, slot: true},
    {number: 7, isVip: false, slot: true},
    {number: 8, isVip: false, slot: true},
    {number: 9, isVip: false, slot: true},
    {number: 10, isVip: false, slot: true},
    {number: 11, isVip: false, slot: true},
    {number: 12, isVip: false, slot: true},
    {number: 13, isVip: false, slot: true},
    {number: 14, isVip: false, slot: true},
    {number: 15, isVip: false, slot: true},
    {number: 16, isVip: false, slot: true},
    {number: 17, isVip: false, slot: true},
    {number: 18, isVip: false, slot: true},
    {number: 19, isVip: false, slot: true},
    {number: 20, isVip: false, slot: true},
    {number: 21, isVip: false, slot: true},
    {number: 22, isVip: false, slot: true},
    {number: 23, isVip: false, slot: true},
    {number: 24, isVip: false, slot: true},
    {number: 25, isVip: false, slot: true}],
  C: [{number: 1, isVip: false, slot: true},
{number: 2, isVip: false, slot: true},
{number: 3, isVip: false, slot: true},
{number: 4, isVip: false, slot: true},
{number: 5, isVip: false, slot: true},
{number: 6, isVip: false, slot: true},
{number: 7, isVip: false, slot: true},
{number: 8, isVip: false, slot: true},
{number: 9, isVip: false, slot: true},
{number: 10, isVip: false, slot: true},
{number: 11, isVip: false, slot: true},
{number: 12, isVip: false, slot: true},
{number: 13, isVip: false, slot: true},
{number: 14, isVip: false, slot: true},
{number: 15, isVip: false, slot: true},
{number: 16, isVip: false, slot: true},
{number: 17, isVip: false, slot: true},
{number: 18, isVip: false, slot: true},
{number: 19, isVip: false, slot: true},
{number: 20, isVip: false, slot: true},
{number: 21, isVip: false, slot: true},
{number: 22, isVip: false, slot: true},
{number: 23, isVip: false, slot: true},
{number: 24, isVip: false, slot: true},
{number: 25, isVip: false, slot: true}],
  D: [{number: 1, isVip: false, slot: true},
{number: 2, isVip: false, slot: true},
{number: 3, isVip: false, slot: true},
{number: 4, isVip: false, slot: true},
{number: 5, isVip: false, slot: true},
{number: 6, isVip: false, slot: true},
{number: 7, isVip: false, slot: true},
{number: 8, isVip: false, slot: true},
{number: 9, isVip: false, slot: true},
{number: 10, isVip: false, slot: true},
{number: 11, isVip: false, slot: true},
{number: 12, isVip: false, slot: true},
{number: 13, isVip: false, slot: true},
{number: 14, isVip: false, slot: true},
{number: 15, isVip: false, slot: true},
{number: 16, isVip: false, slot: true},
{number: 17, isVip: false, slot: true},
{number: 18, isVip: false, slot: true},
{number: 19, isVip: false, slot: true},
{number: 20, isVip: false, slot: true},
{number: 21, isVip: false, slot: true},
{number: 22, isVip: false, slot: true},
{number: 23, isVip: false, slot: true},
{number: 24, isVip: false, slot: true},
{number: 25, isVip: false, slot: true}],
  E: [{number: 1, isVip: false, slot: true},
{number: 2, isVip: false, slot: true},
{number: 3, isVip: false, slot: true},
{number: 4, isVip: false, slot: true},
{number: 5, isVip: false, slot: true},
{number: 6, isVip: false, slot: true},
{number: 7, isVip: false, slot: true},
{number: 8, isVip: false, slot: true},
{number: 9, isVip: false, slot: true},
{number: 10, isVip: false, slot: true},
{number: 11, isVip: false, slot: true},
{number: 12, isVip: false, slot: true},
{number: 13, isVip: false, slot: true},
{number: 14, isVip: false, slot: true},
{number: 15, isVip: false, slot: true},
{number: 16, isVip: false, slot: true},
{number: 17, isVip: false, slot: true},
{number: 18, isVip: false, slot: true},
{number: 19, isVip: false, slot: true},
{number: 20, isVip: false, slot: true},
{number: 21, isVip: false, slot: true},
{number: 22, isVip: false, slot: true},
{number: 23, isVip: false, slot: true},
{number: 24, isVip: false, slot: true},
{number: 25, isVip: false, slot: true}],
  F: [{number: 1, isVip: false, slot: true},
    {number: 2, isVip: false, slot: true},
    {number: 3, isVip: false, slot: true},
    {number: 4, isVip: false, slot: true},
    {number: 5, isVip: false, slot: true},
    {number: 6, isVip: false, slot: true},
    {number: 7, isVip: false, slot: true},
    {number: 8, isVip: false, slot: true},
    {number: 9, isVip: false, slot: true},
    {number: 10, isVip: false, slot: true},
    {number: 11, isVip: false, slot: true},
    {number: 12, isVip: false, slot: true},
    {number: 13, isVip: false, slot: true},
    {number: 14, isVip: false, slot: true},
    {number: 15, isVip: false, slot: true},
    {number: 16, isVip: false, slot: true},
    {number: 17, isVip: false, slot: true},
    {number: 18, isVip: false, slot: true},
    {number: 19, isVip: false, slot: true},
    {number: 20, isVip: false, slot: true},
    {number: 21, isVip: false, slot: true},
    {number: 22, isVip: false, slot: true},
    {number: 23, isVip: false, slot: true},
    {number: 24, isVip: false, slot: true},
    {number: 25, isVip: false, slot: true}]
};


// tslint:disable-next-line: one-variable-per-declaration
export const DeltaA320_200_1Seats: any = {
  VIP1: {
    A: [{number: 1, isVip: true, slot: true},
      {number: 2, isVip: true, slot: true},
      {number: 3, isVip: true, slot: true}],
    B: [{number: 1, isVip: true, slot: true},
        {number: 2, isVip: true, slot: true},
        {number: 3, isVip: true, slot: true}],
  },
  VIP2: {
    C: [{number: 1, isVip: true, slot: true},
      {number: 2, isVip: true, slot: true},
      {number: 3, isVip: true, slot: true}],
    D: [{number: 1, isVip: true, slot: true},
        {number: 2, isVip: true, slot: true},
        {number: 3, isVip: true, slot: true}],
  },
  I:{
    A: [    {number: 4, isVip: false, slot: true},
      {number: 5, isVip: false, slot: true},
      {number: 6, isVip: false, slot: true},
      {number: 7, isVip: false, slot: true},
      {number: 8, isVip: false, slot: true},
      {number: 9, isVip: false, slot: true},],
    B: [    {number: 4, isVip: false, slot: true},
      {number: 5, isVip: false, slot: true},
      {number: 6, isVip: false, slot: true},
      {number: 7, isVip: false, slot: true},
      {number: 8, isVip: false, slot: true},
      {number: 9, isVip: false, slot: true},],
    C: [    {number: 4, isVip: false, slot: true},
      {number: 5, isVip: false, slot: true},
      {number: 6, isVip: false, slot: true},
      {number: 7, isVip: false, slot: true},
      {number: 8, isVip: false, slot: true},
      {number: 9, isVip: false, slot: true},],
  },
  II:{
    D: [    {number: 4, isVip: false, slot: true},
      {number: 5, isVip: false, slot: true},
      {number: 6, isVip: false, slot: true},
      {number: 7, isVip: false, slot: true},
      {number: 8, isVip: false, slot: true},
      {number: 9, isVip: false, slot: true},],
    E: [    {number: 4, isVip: false, slot: true},
      {number: 5, isVip: false, slot: true},
      {number: 6, isVip: false, slot: true},
      {number: 7, isVip: false, slot: true},
      {number: 8, isVip: false, slot: true},
      {number: 9, isVip: false, slot: true},],
    F: [    {number: 4, isVip: false, slot: true},
      {number: 5, isVip: false, slot: true},
      {number: 6, isVip: false, slot: true},
      {number: 7, isVip: false, slot: true},
      {number: 8, isVip: false, slot: true},
      {number: 9, isVip: false, slot: true},],
  },
  III:{
    A:[{number: 10, isVip: false, slot: true}],
    B:[{number: 10, isVip: false, slot: true}],
    C:[{number: 10, isVip: false, slot: true}],
  },
  IV:{
    D:[{number: 10, isVip: false, slot: true}],
    E:[{number: 10, isVip: false, slot: true}],
    F:[{number: 10, isVip: false, slot: true}],
  },
  V:{
    A:[{number: 11, isVip: false, slot: true},
      {number: 12, isVip: false, slot: true},
      {number: 13, isVip: false, slot: true},
      {number: 14, isVip: false, slot: true},
      {number: 15, isVip: false, slot: true},
      {number: 16, isVip: false, slot: true},
      {number: 17, isVip: false, slot: true},
      {number: 18, isVip: false, slot: true},
      {number: 19, isVip: false, slot: true},
      {number: 20, isVip: false, slot: true},
      {number: 21, isVip: false, slot: true},
      {number: 22, isVip: false, slot: true},
      {number: 23, isVip: false, slot: true},
      {number: 24, isVip: false, slot: true},
      {number: 25, isVip: false, slot: true},
      {number: 26, isVip: false, slot: true},
    ],
    B:[{number: 11, isVip: false, slot: true},
      {number: 12, isVip: false, slot: true},
      {number: 13, isVip: false, slot: true},
      {number: 14, isVip: false, slot: true},
      {number: 15, isVip: false, slot: true},
      {number: 16, isVip: false, slot: true},
      {number: 17, isVip: false, slot: true},
      {number: 18, isVip: false, slot: true},
      {number: 19, isVip: false, slot: true},
      {number: 20, isVip: false, slot: true},
      {number: 21, isVip: false, slot: true},
      {number: 22, isVip: false, slot: true},
      {number: 23, isVip: false, slot: true},
      {number: 24, isVip: false, slot: true},
      {number: 25, isVip: false, slot: true},
      {number: 26, isVip: false, slot: true},
    ],
    C:[{number: 11, isVip: false, slot: true},
      {number: 12, isVip: false, slot: true},
      {number: 13, isVip: false, slot: true},
      {number: 14, isVip: false, slot: true},
      {number: 15, isVip: false, slot: true},
      {number: 16, isVip: false, slot: true},
      {number: 17, isVip: false, slot: true},
      {number: 18, isVip: false, slot: true},
      {number: 19, isVip: false, slot: true},
      {number: 20, isVip: false, slot: true},
      {number: 21, isVip: false, slot: true},
      {number: 22, isVip: false, slot: true},
      {number: 23, isVip: false, slot: true},
      {number: 24, isVip: false, slot: true},
      {number: 25, isVip: false, slot: true},
      {number: 26, isVip: false, slot: true},
    ],
  },
  VI:{
    D:[{number: 11, isVip: false, slot: true},
      {number: 12, isVip: false, slot: true},
      {number: 13, isVip: false, slot: true},
      {number: 14, isVip: false, slot: true},
      {number: 15, isVip: false, slot: true},
      {number: 16, isVip: false, slot: true},
      {number: 17, isVip: false, slot: true},
      {number: 18, isVip: false, slot: true},
      {number: 19, isVip: false, slot: true},
      {number: 20, isVip: false, slot: true},
      {number: 21, isVip: false, slot: true},
      {number: 22, isVip: false, slot: true},
      {number: 23, isVip: false, slot: true},
      {number: 24, isVip: false, slot: true},
      {number: 25, isVip: false, slot: true},
      {number: 26, isVip: false, slot: true},
    ],
    E:[{number: 11, isVip: false, slot: true},
      {number: 12, isVip: false, slot: true},
      {number: 13, isVip: false, slot: true},
      {number: 14, isVip: false, slot: true},
      {number: 15, isVip: false, slot: true},
      {number: 16, isVip: false, slot: true},
      {number: 17, isVip: false, slot: true},
      {number: 18, isVip: false, slot: true},
      {number: 19, isVip: false, slot: true},
      {number: 20, isVip: false, slot: true},
      {number: 21, isVip: false, slot: true},
      {number: 22, isVip: false, slot: true},
      {number: 23, isVip: false, slot: true},
      {number: 24, isVip: false, slot: true},
      {number: 25, isVip: false, slot: true},
      {number: 26, isVip: false, slot: true},
    ],
    F:[{number: 11, isVip: false, slot: true},
      {number: 12, isVip: false, slot: true},
      {number: 13, isVip: false, slot: true},
      {number: 14, isVip: false, slot: true},
      {number: 15, isVip: false, slot: true},
      {number: 16, isVip: false, slot: true},
      {number: 17, isVip: false, slot: true},
      {number: 18, isVip: false, slot: true},
      {number: 19, isVip: false, slot: true},
      {number: 20, isVip: false, slot: true},
      {number: 21, isVip: false, slot: true},
      {number: 22, isVip: false, slot: true},
      {number: 23, isVip: false, slot: true},
      {number: 24, isVip: false, slot: true},
      {number: 25, isVip: false, slot: true},
      {number: 26, isVip: false, slot: true},
    ],
  },
}